services:
  nginx-proxy:
    build: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/tmp/default.conf
    environment:
      - FLASK_SERVER_ADDR=flask-app:8100
    ports:
      - "81:81"
    depends_on:
      - flask-app
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:81/health-check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    command: /app/start.sh
  flask-app:
    build: flask
    restart: always
    ports:
      - '8100:8100'
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8100/flask-health-check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3

    command: gunicorn -w 3 -t 60 --bind 0.0.0.0:8100 wsgi:app
